In [88]:
import pandas as pd

In [89]:
from sklearn.tree import DecisionTreeClassifier

In [90]:
from sklearn.ensemble import RandomForestClassifier

In [91]:
from sklearn import svm

In [92]:
from sklearn.model_selection import train_test_split

In [93]:
from sklearn import metrics

In [94]:
dataset = pd.read_csv("CE802_P2_Data.csv")
dataset.head()

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,Class
0,20,-21.42,13.1,464.04,-6.10,-4.50,-18.66,27.54,20.1,-7.08,-16.32,365,0.47,3.40,-3.90,False
1,20,-27.12,13.5,299.04,-6.18,-4.91,-18.66,27.44,18.2,-12.84,-11.07,205,-129.53,7.12,NaN,False
2,20,-33.87,10.5,854.04,-9.32,-7.16,-18.66,25.44,11.9,-5.46,-11.01,330,-44.53,4.62,-3.84,False
3,20,-25.38,19.4,809.04,-12.69,-4.95,-23.66,25.54,19.6,-11.31,-7.53,215,-54.53,2.26,NaN,False
4,20,-23.22,16.0,359.04,-7.70,-4.36,-8.66,26.64,25.8,-12.69,-10.20,85,-134.53,-0.20,-7.76,True

In [95]:
datasetMean = dataset.fillna(dataset.mean())
# Experimenting without F15 column 
# X= datasetMean.loc[:, :'F14']

X= datasetMean.loc[:, :'F15']
Y= datasetMean['Class']

# Experimenting with median value
# datasetMedian = dataset.fillna(dataset.median()) 
# X= datasetMedian.loc[:, :'F15']
# Y= datasetMedian['Class']

#  a) Investigate the performance of decision tree classifier

In [96]:
#split data into training and test set
X_train_DT, X_test_DT, y_train_DT, y_test_DT = train_test_split(X, Y, test_size = 0.10, random_state= 105)

#Create decision tree classifier object
decTreeClassObj = DecisionTreeClassifier(random_state=0)

#Training deciosion tree classifier
decTreeClassObj = decTreeClassObj.fit(X_train_DT, y_train_DT)

#predict the result for test dataset
y_Prediction_DT = decTreeClassObj.predict(X_test_DT)

# Model Performance, how often is the classifier correct
print("Accuracy:", metrics.accuracy_score(y_test_DT, y_Prediction_DT))

print("Precision:", metrics.precision_score(y_test_DT, y_Prediction_DT))

print("Recall:", metrics.recall_score(y_test_DT, y_Prediction_DT))

Accuracy: 0.84
Precision: 0.8484848484848485
Recall: 0.8

# a) Investigate the performance of Random Forest Classifier

In [97]:
#split data into training and test set
X_train_RFC, X_test_RFC, y_train_RFC, y_test_RFC = train_test_split(X, Y, test_size = 0.1, random_state= 105)

#Create a Gaussian classifier
rfClassObj = RandomForestClassifier(n_estimators=200, random_state=0)

#Training deciosion tree classifier
rfClassObj = rfClassObj.fit(X_train_RFC, y_train_RFC)

#predict the result for test dataset
y_Prediction_RFC = rfClassObj.predict(X_test_RFC)

# Model Accuracy, how often is the classifier correct
print("Accuracy:", metrics.accuracy_score(y_test_RFC, y_Prediction_RFC))

print("Precision:", metrics.precision_score(y_test_RFC, y_Prediction_RFC))

print("Recall:", metrics.recall_score(y_test_RFC, y_Prediction_RFC))

Accuracy: 0.9333333333333333
Precision: 0.9285714285714286
Recall: 0.9285714285714286

# a) Investigate the performance of svm classifier

In [98]:
#split data into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.1, random_state= 105)

#Create a svm classifier
svmClassObj = svm.SVC(kernel='linear') #using linear Kernel

#Training svm classifier using training sets
svmClassObj.fit(X_train, y_train)

#predict the result for test dataset
y_Prediction = svmClassObj.predict(X_test)

# Model Accuracy
print("Accuracy:",metrics.accuracy_score(y_test, y_Prediction))

print("Precision:", metrics.precision_score(y_test, y_Prediction))

print("Recall:", metrics.recall_score(y_test, y_Prediction))

Accuracy: 0.9133333333333333
Precision: 0.9130434782608695
Recall: 0.9

# b) Prediction on a hold-out test set using Random Forest

In [99]:
datasetTest = pd.read_csv("CE802_P2_Test.csv")

datasetMeanTest = datasetTest.fillna(datasetTest.mean())

X_Testset= datasetMeanTest.loc[:, :'F15']

#split data into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.1, random_state= 105)

# Create a Random Forest Classifier object
rfClassObj = RandomForestClassifier(n_estimators=200, random_state=0)

#Training Random Forest Classifier using training sets
rfClassObj.fit(X_train, y_train)

#predict the result for test dataset
y_Prediction = rfClassObj.predict(X_Testset)

datasetMeanTest['Class'] = y_Prediction


#Save the new results in a new file CE802_P2_Test.csv
datasetMeanTest.to_csv("CE802_P2_Test_V2.csv", index=False)
datasetMeanTest

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,Class
0,2,-38.31,1.62,248.04,-11.74,-9.25,-5.66,16.40,2.92,1.17,-13.14,2,-74.53,9.18,-5.876347,True
1,20,-24.03,11.40,629.04,-8.02,-5.35,-28.66,27.14,16.70,-10.56,-8.67,15,-14.53,2.06,-5.876347,False
2,2,-45.06,1.84,206.04,-11.73,-9.28,-7.66,15.94,1.70,-1.77,-20.37,3,-40.53,7.12,-5.876347,True
3,20,-22.35,18.30,539.04,-7.14,-4.15,-28.66,27.14,11.70,-14.97,-8.55,195,-29.53,1.46,-6.930000,True
4,20,-22.47,10.70,749.04,-7.13,-4.60,-8.66,35.14,28.70,-12.33,-10.47,285,-74.53,-1.74,-5.876347,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,20,-22.80,14.80,329.04,-5.88,-4.92,-18.66,25.34,13.70,-14.28,-10.98,195,-29.53,3.28,-5.876347,False
1496,2,-37.11,1.48,239.04,-14.27,-10.03,-3.66,16.34,3.02,-1.08,-11.28,20,-75.53,10.10,-5.876347,True
1497,2,-35.67,0.20,200.04,-10.59,-12.15,-7.66,16.42,1.92,-1.08,-9.57,20,-46.53,10.46,-5.876347,True
1498,2,-36.21,1.62,275.04,-11.82,-8.89,-5.66,16.64,1.82,0.36,-11.22,6,-60.53,9.24,-5.876347,True
1499,20,-19.83,17.10,659.04,-6.62,-5.59,-18.66,28.94,20.70,-13.05,-18.54,130,-114.53,-2.22,-6.120000,True