In [1]:
from sklearn.ensemble import RandomForestRegressor

In [2]:
from sklearn.datasets import make_regression

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
from sklearn.svm import SVR

In [5]:
from sklearn.pipeline import make_pipeline

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
import pandas as pd

In [9]:
import numpy as np

In [10]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# 3 a) Investigate the performance using machine learning procedures

In [11]:
dataset = pd.read_csv("CE802_P3_Data.csv")

In [12]:
#Change the string values in column F5 and F6 to numerical values
datasetF5 = pd.factorize(dataset['F5'])
dataset['F5'] = datasetF5[0]
datasetF6= pd.factorize(dataset['F6'])
dataset['F6'] = datasetF6[0]

dataset.head()

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,F16,Target
0,11.85,-258.09,-6.95,2557.29,0,0,7.59,-28.22,-259.22,-1578.12,-141.76,9,6,20.19,169.26,1.64,999.41
1,11.99,-169.71,-16.06,2862.87,0,1,2.57,-13.76,-321.80,-1914.16,-165.83,6,6,9.51,6259.05,0.08,0.00
2,3.48,-317.76,-8.14,2175.81,1,2,1.60,-32.76,-253.54,457.12,-203.87,15,10,7.02,38504.82,6.40,266.29
3,14.75,-394.26,-5.61,1927.86,0,2,7.33,-13.42,-149.86,-1972.04,-145.52,6,10,33.99,20883.90,21.98,598.77
4,10.25,-365.46,-10.33,3187.98,2,3,4.37,-32.66,-224.58,-2022.36,-153.94,12,10,4.29,12095.91,2167.48,396.90

In [13]:
X = dataset.loc[:, :'F16']
Y= dataset['Target']

# 3 a) Investigate the performance using Linear Regression

In [16]:
#split data into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.1, random_state= 0)

#Create linear regression object
linRegClassObj = LinearRegression()

#Train the model using training sets
linRegClassObj.fit(X_train, y_train)

#predict the result for test dataset
y_Prediction = linRegClassObj.predict(X_test)

# The mean squared error
print('Mean Squared Error: ', mean_squared_error(y_test, y_Prediction))

# The mean absolute error
print('Mean Absolute Error: ', mean_absolute_error(y_test, y_Prediction))

# RMSE for Linear Regression
print('RMSE for Linear Regression', np.sqrt(mean_squared_error(y_test, y_Prediction)))

# The coefficient of determination 
print('Coefficient of determination: ', r2_score(y_test, y_Prediction))

Mean Squared Error:  327750.85669804417
Mean absolute error:  428.1723776572883
RMSE for Linear Regression 572.4952896732375
Coefficient of determination:  0.7191719295401922

# 3 a) Investigate the performance using Random Forest Regression

In [17]:
#split data into training and test set
X_train_RFR, X_test_RFR, y_train_RFR, y_test_RFR = train_test_split(X, Y, test_size = 0.1, random_state= 1)

#Create random forest object
regr = RandomForestRegressor(max_depth=15, random_state=115)

#Train the model using training sets
regr.fit(X_train_RFR, y_train_RFR)

#predict the result for test dataset
y_Prediction_RFR = regr.predict(X_test_RFR)

# The mean squared error
print('Mean Squared Error: ', mean_squared_error(y_test_RFR, y_Prediction_RFR))

# The mean absolute error
print('Mean absolute error: ', mean_absolute_error(y_test_RFR, y_Prediction_RFR))

# RMSE for Random Forest Regression
print('RMSE for Random Forest Regression', np.sqrt(mean_squared_error(y_test_RFR, y_Prediction_RFR)))

# The coefficient of determination 
print('Coefficient of determination: ', r2_score(y_test_RFR, y_Prediction_RFR))

Mean Squared Error:  314320.52758747403
Mean absolute error:  417.697962540787
RMSE for Random Forest Regression 560.6429590991704
Coefficient of determination:  0.6951721131137925

# 3 a) Investigate the performance using Support Vector Regression

In [18]:
#split data into training and test set
X_train_SVR, X_test_SVR, y_train_SVR, y_test_SVR = train_test_split(X, Y, test_size = 0.1, random_state= 120)
svRegr = make_pipeline(StandardScaler(), SVR(C=1190.0, epsilon=0.1))

# #Train the model using training sets
svRegr.fit(X_train_SVR, y_train_SVR)

# #predict the result for test dataset
y_Prediction_SVR = svRegr.predict(X_test_SVR)

# The mean squared error
print('Mean Squared Error: ', mean_squared_error(y_test_SVR, y_Prediction_SVR))

# The mean absolute error
print('Mean absolute error: ', mean_absolute_error(y_test_SVR, y_Prediction_SVR))

# RMSE for Support Vector Machine Regression
print('RMSE for Support Vector Machine Regression', np.sqrt(mean_squared_error(y_test_SVR, y_Prediction_SVR)))

# The coefficient of determination 
print('Coefficient of determination: ', r2_score(y_test_SVR, y_Prediction_SVR))

Mean Squared Error:  287400.42994923535
Mean absolute error:  383.1276337808719
RMSE for Support Vector Machine Regression 536.0974071465328
Coefficient of determination:  0.7657963497776105

# b) Prediction on a hold-out test set using Support Vector Regression

In [19]:
datasetTest = pd.read_csv("CE802_P3_Test.csv")

datasetTestF5 = pd.factorize(datasetTest['F5'])
datasetTest['F5'] = datasetTestF5[0]
datasetTestF6= pd.factorize(datasetTest['F6'])
datasetTest['F6'] = datasetTestF6[0]

X_Test = datasetTest.loc[:, :'F16']

#split data into training and test set
X_train_SVR, X_test_SVR, y_train_SVR, y_test_SVR = train_test_split(X, Y, test_size = 0.1, random_state= 120)
svRegr = make_pipeline(StandardScaler(), SVR(C=1190.0, epsilon=0.1))


#Train the model using training sets
svRegr.fit(X_train_SVR, y_train_SVR)

#predict the result for test dataset
y_Prediction_SVR_Test = svRegr.predict(X_Test)

datasetTest['Target'] = y_Prediction_SVR_Test

#Save the new results in a new file CE802_P3_Test.csv
datasetTest.to_csv("CE802_P3_Test_V2.csv", index=False)

datasetTest

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,F16,Target
0,11.23,-195.54,-1.19,1468.56,0,0,8.97,-23.62,-249.36,-854.18,-155.20,12,10,12.39,-3480.87,0.04,419.413232
1,14.89,-426.24,-1.18,3049.08,0,0,6.33,-39.26,-226.26,-2126.68,-159.42,9,8,5.19,8831.19,43.68,100.331235
2,6.76,-493.47,-13.55,3197.13,1,0,1.77,-25.84,-238.30,-2270.78,-212.73,12,10,3.30,-4468.44,0.52,1211.226175
3,15.12,-320.04,-12.17,2436.00,1,1,5.42,-17.32,-203.64,-304.24,-100.34,18,12,6.51,22851.60,758.54,1069.717348
4,10.12,-387.99,-7.11,2800.89,1,2,1.39,-12.78,-265.16,-1419.76,-137.49,0,14,14.22,24396.09,0.68,-156.573893
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,6.04,-308.37,-12.30,4346.82,2,0,8.96,-18.28,-266.14,-3132.76,-91.62,9,8,15.63,-1231.92,8.32,1166.215668
1496,14.13,-280.62,-6.00,2600.13,0,2,2.70,-0.80,-101.86,-1305.60,-147.74,18,18,13.23,7516.71,0.78,-13.922319
1497,13.03,-301.05,-5.22,2279.07,1,1,0.23,-17.06,-168.30,-1413.06,-102.67,0,14,8.58,9689.01,4.80,96.071321
1498,3.29,-347.40,-7.19,1985.31,1,2,2.63,-22.20,-299.66,-1183.62,-118.93,6,8,6.21,-2832.51,0.46,-248.879259
1499,1.96,-456.06,-7.08,2821.95,4,3,7.75,-14.40,-176.46,-1754.88,-210.39,15,8,3.30,5500.77,0.00,1386.475635